CREATE TABLE lists (
  list_id SERIAL PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  time_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  time_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id)
    REFERENCES users(user_id)
      ON DELETE CASCADE
);
