CREATE TABLE entries (
  entry_id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  score INT NOT NULL,
  time_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  time_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  list_id INT NOT NULL,
  FOREIGN KEY (list_id)
    REFERENCES lists(list_id)
      ON DELETE CASCADE
);
